/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca.ui;

/**
 *
 * @author asael
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdAddLibro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtNoCopias = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        ftxtFechaPublicacion = new javax.swing.JFormattedTextField();
        ftxtCodigo = new javax.swing.JFormattedTextField();
        btnAddLibro = new javax.swing.JButton();
        btnVerListadoL = new javax.swing.JButton();
        btnCancelarL = new javax.swing.JButton();
        jdAddEstudiante = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        ftxtCodCarrera = new javax.swing.JFormattedTextField();
        ftxtFechaNac = new javax.swing.JFormattedTextField();
        btnAddEst = new javax.swing.JButton();
        btnCancelarEst = new javax.swing.JButton();
        btnVerListadoE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jdAddPrestamo = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCarnetPrestamo = new javax.swing.JTextField();
        ftxtCodPrestamo = new javax.swing.JFormattedTextField();
        btnPrestar = new javax.swing.JButton();
        btnCancelarP = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLibros = new javax.swing.JMenu();
        itmAddLibros = new javax.swing.JMenuItem();
        itmAddCopias = new javax.swing.JMenuItem();
        itmVerListLibros = new javax.swing.JMenuItem();
        menuEstudiante = new javax.swing.JMenu();
        itmAddEstudiante = new javax.swing.JMenuItem();
        itmVerListEst = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        itmAddPrestamo = new javax.swing.JMenuItem();
        itmDevolucion = new javax.swing.JMenuItem();
        menuListados = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();

        jdAddLibro.setModal(true);
        jdAddLibro.setSize(new java.awt.Dimension(350, 250));

        jLabel1.setText("Codigo:");

        jLabel2.setText("Autor:");

        jLabel3.setText("Título:");

        jLabel4.setText("No.Copias");

        jLabel5.setText("Fecha Publicacion:");

        jLabel6.setText("Editorial");

        try {
            ftxtFechaPublicacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaPublicacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        try {
            ftxtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAddLibro.setText("Agregar");

        btnVerListadoL.setText("Ver Listado");

        btnCancelarL.setText("Cancelar");

        javax.swing.GroupLayout jdAddLibroLayout = new javax.swing.GroupLayout(jdAddLibro.getContentPane());
        jdAddLibro.getContentPane().setLayout(jdAddLibroLayout);
        jdAddLibroLayout.setHorizontalGroup(
            jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jdAddLibroLayout.createSequentialGroup()
                        .addComponent(btnAddLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerListadoL))
                    .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdAddLibroLayout.createSequentialGroup()
                            .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jdAddLibroLayout.createSequentialGroup()
                                    .addComponent(ftxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNoCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtAutor)
                                .addComponent(txtTitulo)
                                .addComponent(txtEditorial)))
                        .addGroup(jdAddLibroLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(84, 84, 84)
                            .addComponent(ftxtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jdAddLibroLayout.setVerticalGroup(
            jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerListadoL)
                    .addComponent(btnAddLibro)
                    .addComponent(btnCancelarL))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jdAddEstudiante.setSize(new java.awt.Dimension(510, 190));

        jLabel7.setText("Carnet:");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Codigo de carrera:");

        jLabel10.setText("Fecha Nacimiento:");

        try {
            ftxtCodCarrera.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodCarrera.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAddEst.setText("Agregar");

        btnCancelarEst.setText("Cancelar");

        btnVerListadoE.setText("Ver Listado");

        jLabel11.setText("mensaje");
        jLabel11.setVisible(false);

        javax.swing.GroupLayout jdAddEstudianteLayout = new javax.swing.GroupLayout(jdAddEstudiante.getContentPane());
        jdAddEstudiante.getContentPane().setLayout(jdAddEstudianteLayout);
        jdAddEstudianteLayout.setHorizontalGroup(
            jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerListadoE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEst))
                    .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                        .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                                .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddEst))
                            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftxtCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jdAddEstudianteLayout.setVerticalGroup(
            jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ftxtCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEst)
                    .addComponent(btnVerListadoE)
                    .addComponent(jLabel11))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jdAddPrestamo.setSize(new java.awt.Dimension(300, 150));

        jLabel12.setText("Codigo del Libro:");

        jLabel13.setText("Carnet del estudiante:");

        try {
            ftxtCodPrestamo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodPrestamo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPrestar.setText("Prestar");

        btnCancelarP.setText("Cancelar");

        javax.swing.GroupLayout jdAddPrestamoLayout = new javax.swing.GroupLayout(jdAddPrestamo.getContentPane());
        jdAddPrestamo.getContentPane().setLayout(jdAddPrestamoLayout);
        jdAddPrestamoLayout.setHorizontalGroup(
            jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdAddPrestamoLayout.createSequentialGroup()
                        .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtCodPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txtCarnetPrestamo)))
                    .addGroup(jdAddPrestamoLayout.createSequentialGroup()
                        .addComponent(btnCancelarP)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrestar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jdAddPrestamoLayout.setVerticalGroup(
            jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCarnetPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ftxtCodPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarP)
                    .addComponent(btnPrestar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 400));

        menuLibros.setText("Libros");

        itmAddLibros.setText("Ingresar Libro");
        itmAddLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddLibrosActionPerformed(evt);
            }
        });
        menuLibros.add(itmAddLibros);

        itmAddCopias.setText("Añadir Copias");
        menuLibros.add(itmAddCopias);

        itmVerListLibros.setText("Ver Listado");
        menuLibros.add(itmVerListLibros);

        jMenuBar1.add(menuLibros);

        menuEstudiante.setText("Estuiantes");

        itmAddEstudiante.setText("Ingresar Estudiante");
        itmAddEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddEstudianteActionPerformed(evt);
            }
        });
        menuEstudiante.add(itmAddEstudiante);

        itmVerListEst.setText("Ver Listado");
        menuEstudiante.add(itmVerListEst);

        jMenuBar1.add(menuEstudiante);

        menuPrestamos.setText("Prestamos");

        itmAddPrestamo.setText("Nuevo Prestamo");
        itmAddPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddPrestamoActionPerformed(evt);
            }
        });
        menuPrestamos.add(itmAddPrestamo);

        itmDevolucion.setText("Devolucion");
        menuPrestamos.add(itmDevolucion);

        jMenuBar1.add(menuPrestamos);

        menuListados.setText("Listados");
        jMenuBar1.add(menuListados);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddLibrosActionPerformed
        abrirDialogo(jdAddLibro, "Ingreso de libros");
    }//GEN-LAST:event_itmAddLibrosActionPerformed

    private void itmAddEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddEstudianteActionPerformed
        abrirDialogo(jdAddEstudiante, "Ingreso de estudiantes");
    }//GEN-LAST:event_itmAddEstudianteActionPerformed

    private void itmAddPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddPrestamoActionPerformed
        abrirDialogo(jdAddPrestamo, "Nuevo Prestamo");
    }//GEN-LAST:event_itmAddPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEst;
    private javax.swing.JButton btnAddLibro;
    private javax.swing.JButton btnCancelarEst;
    private javax.swing.JButton btnCancelarL;
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnVerListadoE;
    private javax.swing.JButton btnVerListadoL;
    private javax.swing.JFormattedTextField ftxtCodCarrera;
    private javax.swing.JFormattedTextField ftxtCodPrestamo;
    private javax.swing.JFormattedTextField ftxtCodigo;
    private javax.swing.JFormattedTextField ftxtFechaNac;
    private javax.swing.JFormattedTextField ftxtFechaPublicacion;
    private javax.swing.JMenuItem itmAddCopias;
    private javax.swing.JMenuItem itmAddEstudiante;
    private javax.swing.JMenuItem itmAddLibros;
    private javax.swing.JMenuItem itmAddPrestamo;
    private javax.swing.JMenuItem itmDevolucion;
    private javax.swing.JMenuItem itmVerListEst;
    private javax.swing.JMenuItem itmVerListLibros;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDialog jdAddEstudiante;
    private javax.swing.JDialog jdAddLibro;
    private javax.swing.JDialog jdAddPrestamo;
    private javax.swing.JMenu menuEstudiante;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenu menuListados;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCarnetPrestamo;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtNoCopias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    
    private void abrirDialogo(javax.swing.JDialog jd, String title){
        jd.setTitle(title);
        jd.setLocationRelativeTo(null);
        jd.setResizable(false);
        jd.setVisible(true);
    }
   
}
