package sistemabiblioteca.ui;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import sistemabiblioteca.backend.Archivos.FileController;
import sistemabiblioteca.backend.Core;
import sistemabiblioteca.backend.Estudiante;
import sistemabiblioteca.backend.Libro;

public class Interfaz extends javax.swing.JFrame {
    private Libro libro;
    private Estudiante estudiante;
    private Core core = new Core();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdAddLibro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtNoCopias = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        ftxtFechaPublicacion = new javax.swing.JFormattedTextField();
        ftxtCodigo = new javax.swing.JFormattedTextField();
        btnAddLibro = new javax.swing.JButton();
        btnVerListadoL = new javax.swing.JButton();
        btnCancelarL = new javax.swing.JButton();
        lblErrorL = new javax.swing.JLabel();
        jdAddEstudiante = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        ftxtFechaNac = new javax.swing.JFormattedTextField();
        btnAddEst = new javax.swing.JButton();
        btnCancelarEst = new javax.swing.JButton();
        btnVerListadoE = new javax.swing.JButton();
        lblErrorE = new javax.swing.JLabel();
        txtCodCarrera = new javax.swing.JTextField();
        jdAddPrestamo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        btnPrestar = new javax.swing.JButton();
        btnCancelarP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCarnetPrestamo = new javax.swing.JTextField();
        ftxtCodPrestamo1 = new javax.swing.JFormattedTextField();
        lblErrorP = new javax.swing.JLabel();
        jdListLibros = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListLibros = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cbOpcionFiltroL = new javax.swing.JComboBox<>();
        txtFiltroLibro = new javax.swing.JTextField();
        btnFiltrarL = new javax.swing.JButton();
        btnCleanFiltroL = new javax.swing.JButton();
        jdListEstudiantes = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        cbOpcionFiltroE = new javax.swing.JComboBox<>();
        txtFiltroE = new javax.swing.JTextField();
        btnFiltroE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListEstudiantes = new javax.swing.JTable();
        btnCleanFlitroE = new javax.swing.JButton();
        jdDevolucion = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        txtCarnetDev = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        lblErrorDev = new javax.swing.JLabel();
        ftxtCodigoDev = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLibros = new javax.swing.JMenu();
        itmAddLibros = new javax.swing.JMenuItem();
        itmAddCopias = new javax.swing.JMenuItem();
        itmVerListLibros = new javax.swing.JMenuItem();
        menuEstudiante = new javax.swing.JMenu();
        itmAddEstudiante = new javax.swing.JMenuItem();
        itmVerListEst = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        itmAddPrestamo = new javax.swing.JMenuItem();
        itmDevolucion = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();

        jdAddLibro.setModal(true);
        jdAddLibro.setSize(new java.awt.Dimension(350, 260));

        jLabel1.setText("Codigo:");

        jLabel2.setText("Autor:");

        jLabel3.setText("Título:");

        jLabel4.setText("No.Copias");

        jLabel5.setText("Fecha Publicacion:");

        jLabel6.setText("Editorial");

        try {
            ftxtFechaPublicacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaPublicacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        try {
            ftxtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAddLibro.setText("Agregar");
        btnAddLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLibroActionPerformed(evt);
            }
        });

        btnVerListadoL.setText("Ver Listado");
        btnVerListadoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListadoLActionPerformed(evt);
            }
        });

        btnCancelarL.setText("Cancelar");
        btnCancelarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLActionPerformed(evt);
            }
        });

        lblErrorL.setVisible(false);
        lblErrorL.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblErrorL.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorL.setText("mensajeError");

        javax.swing.GroupLayout jdAddLibroLayout = new javax.swing.GroupLayout(jdAddLibro.getContentPane());
        jdAddLibro.getContentPane().setLayout(jdAddLibroLayout);
        jdAddLibroLayout.setHorizontalGroup(
            jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jdAddLibroLayout.createSequentialGroup()
                            .addComponent(btnAddLibro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnVerListadoL))
                        .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdAddLibroLayout.createSequentialGroup()
                                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jdAddLibroLayout.createSequentialGroup()
                                        .addComponent(ftxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNoCopias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAutor)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtEditorial)))
                            .addGroup(jdAddLibroLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(84, 84, 84)
                                .addComponent(ftxtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblErrorL))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jdAddLibroLayout.setVerticalGroup(
            jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdAddLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerListadoL)
                    .addComponent(btnAddLibro)
                    .addComponent(btnCancelarL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorL)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jdAddLibro.getAccessibleContext().setAccessibleParent(this);

        jdAddEstudiante.setModal(true);
        jdAddEstudiante.setSize(new java.awt.Dimension(500, 190));

        jLabel7.setText("Carnet:");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Codigo de carrera:");

        jLabel10.setText("Fecha Nacimiento:");

        try {
            ftxtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtFechaNac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnAddEst.setText("Agregar");
        btnAddEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEstActionPerformed(evt);
            }
        });

        btnCancelarEst.setText("Cancelar");
        btnCancelarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEstActionPerformed(evt);
            }
        });

        btnVerListadoE.setText("Ver Listado");
        btnVerListadoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListadoEActionPerformed(evt);
            }
        });

        lblErrorE.setVisible(false);
        lblErrorE.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblErrorE.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorE.setText("mensaje");

        javax.swing.GroupLayout jdAddEstudianteLayout = new javax.swing.GroupLayout(jdAddEstudiante.getContentPane());
        jdAddEstudiante.getContentPane().setLayout(jdAddEstudianteLayout);
        jdAddEstudianteLayout.setHorizontalGroup(
            jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                        .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                            .addComponent(btnAddEst)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelarEst)
                            .addGap(18, 18, 18)
                            .addComponent(btnVerListadoE))
                        .addComponent(lblErrorE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jdAddEstudianteLayout.setVerticalGroup(
            jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ftxtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdAddEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEst)
                    .addComponent(btnCancelarEst)
                    .addComponent(btnVerListadoE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jdAddPrestamo.setModal(true);
        jdAddPrestamo.setSize(new java.awt.Dimension(310, 170));

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnCancelarP.setText("Cancelar");
        btnCancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPActionPerformed(evt);
            }
        });

        jLabel12.setText("Codigo del Libros:");

        jLabel13.setText("Carnet del estudiante:");

        try {
            ftxtCodPrestamo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodPrestamo1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblErrorP.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblErrorP.setVisible(false);
        lblErrorP.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorP.setText("Mensaje");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorP)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtCodPrestamo1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(txtCarnetPrestamo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrestar)
                            .addComponent(jLabel12))
                        .addGap(17, 17, 17)
                        .addComponent(btnCancelarP)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCarnetPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ftxtCodPrestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrestar)
                    .addComponent(btnCancelarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorP)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdAddPrestamoLayout = new javax.swing.GroupLayout(jdAddPrestamo.getContentPane());
        jdAddPrestamo.getContentPane().setLayout(jdAddPrestamoLayout);
        jdAddPrestamoLayout.setHorizontalGroup(
            jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdAddPrestamoLayout.setVerticalGroup(
            jdAddPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jdAddPrestamo.getAccessibleContext().setAccessibleParent(this);

        jdListLibros.setModal(true);
        jdListLibros.setSize(new java.awt.Dimension(650, 340));

        tblListLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Autor", "Titulo", "No. Copias", "Fecha publicacion", "Editorial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListLibros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblListLibros);

        jLabel14.setText("Filtrar por:");

        cbOpcionFiltroL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Titulo", "Autor" }));
        cbOpcionFiltroL.setSelectedIndex(-1);

        btnFiltrarL.setText("Filtrar");
        btnFiltrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarLActionPerformed(evt);
            }
        });

        btnCleanFiltroL.setText("Limpiar Filtro");
        btnCleanFiltroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFiltroLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdListLibrosLayout = new javax.swing.GroupLayout(jdListLibros.getContentPane());
        jdListLibros.getContentPane().setLayout(jdListLibrosLayout);
        jdListLibrosLayout.setHorizontalGroup(
            jdListLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdListLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdListLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdListLibrosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOpcionFiltroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltroLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrarL)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanFiltroL)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jdListLibrosLayout.setVerticalGroup(
            jdListLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdListLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdListLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltroLibro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdListLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cbOpcionFiltroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFiltrarL)
                        .addComponent(btnCleanFiltroL)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jdListEstudiantes.setModal(true);
        jdListEstudiantes.setSize(new java.awt.Dimension(620, 390));

        jLabel11.setText("Filtrar:");

        cbOpcionFiltroE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet", "Nombre", "Cod.Carrera" }));
        cbOpcionFiltroE.setSelectedIndex(-1);

        btnFiltroE.setText("Filtrar");
        btnFiltroE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroEActionPerformed(evt);
            }
        });

        tblListEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carnet", "Nombre", "Cod.Carrera", "Fecha Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListEstudiantes);

        btnCleanFlitroE.setText("Limpiar Filtro");
        btnCleanFlitroE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFlitroEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdListEstudiantesLayout = new javax.swing.GroupLayout(jdListEstudiantes.getContentPane());
        jdListEstudiantes.getContentPane().setLayout(jdListEstudiantesLayout);
        jdListEstudiantesLayout.setHorizontalGroup(
            jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdListEstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdListEstudiantesLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOpcionFiltroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtFiltroE, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltroE, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanFlitroE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jdListEstudiantesLayout.setVerticalGroup(
            jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdListEstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFiltroE)
                        .addComponent(btnFiltroE)
                        .addComponent(btnCleanFlitroE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdListEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cbOpcionFiltroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jdDevolucion.setPreferredSize(new java.awt.Dimension(450, 150));
        jdDevolucion.setSize(new java.awt.Dimension(450, 160));

        jLabel15.setText("Carnet del estudiante:");

        jLabel16.setText("Codigo del libro:");

        btnBuscar.setText("Buscar Prestamo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel17.setText("Total a cancelar;");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setText("TOTAL");

        btnFinalizar.setText("Finalizar Prestamo");
        btnFinalizar.setEnabled(false);

        lblErrorDev.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblErrorDev.setVisible(false);
        lblErrorDev.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDev.setText("mensaje");

        try {
            ftxtCodigoDev.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-AAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodigoDev.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jdDevolucionLayout = new javax.swing.GroupLayout(jdDevolucion.getContentPane());
        jdDevolucion.getContentPane().setLayout(jdDevolucionLayout);
        jdDevolucionLayout.setHorizontalGroup(
            jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDevolucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdDevolucionLayout.createSequentialGroup()
                        .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarnetDev)
                            .addComponent(ftxtCodigoDev, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinalizar)))
                    .addGroup(jdDevolucionLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addComponent(lblErrorDev))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jdDevolucionLayout.setVerticalGroup(
            jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDevolucionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCarnetDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnFinalizar)
                    .addComponent(ftxtCodigoDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jdDevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorDev)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 400));

        menuLibros.setText("Libros");

        itmAddLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itmAddLibros.setText("Ingresar Libro");
        itmAddLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddLibrosActionPerformed(evt);
            }
        });
        menuLibros.add(itmAddLibros);

        itmAddCopias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itmAddCopias.setText("Añadir Copias");
        itmAddCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddCopiasActionPerformed(evt);
            }
        });
        menuLibros.add(itmAddCopias);

        itmVerListLibros.setText("Ver Listado");
        menuLibros.add(itmVerListLibros);

        jMenuBar1.add(menuLibros);

        menuEstudiante.setText("Estudiantes");

        itmAddEstudiante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itmAddEstudiante.setText("Ingresar Estudiante");
        itmAddEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddEstudianteActionPerformed(evt);
            }
        });
        menuEstudiante.add(itmAddEstudiante);

        itmVerListEst.setText("Ver Listado");
        menuEstudiante.add(itmVerListEst);

        jMenuBar1.add(menuEstudiante);

        menuPrestamos.setText("Prestamos");

        itmAddPrestamo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itmAddPrestamo.setText("Nuevo Prestamo");
        itmAddPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddPrestamoActionPerformed(evt);
            }
        });
        menuPrestamos.add(itmAddPrestamo);

        itmDevolucion.setText("Devolucion");
        itmDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmDevolucionActionPerformed(evt);
            }
        });
        menuPrestamos.add(itmDevolucion);

        jMenuBar1.add(menuPrestamos);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddLibrosActionPerformed
        abrirDialogo(jdAddLibro, "Ingreso de libros");
    }//GEN-LAST:event_itmAddLibrosActionPerformed

    private void itmAddEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddEstudianteActionPerformed
        abrirDialogo(jdAddEstudiante, "Ingreso de estudiantes");
    }//GEN-LAST:event_itmAddEstudianteActionPerformed

    private void itmAddPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddPrestamoActionPerformed
        abrirDialogo(jdAddPrestamo, "Nuevo Prestamo");
    }//GEN-LAST:event_itmAddPrestamoActionPerformed

    private void btnAddLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLibroActionPerformed
        boolean validacion = true;
        //Verifica que el texto sea un numero
        if (!isNumeric(txtNoCopias.getText())) {
            validacion = false;
        }
        if (!verificarFormatoCodigo(ftxtCodigo.getText())) {
            validacion = false;
            labelError(lblErrorL, "*Formato de codigo incorrecto");
        }
        //Verifica que los campos obligatorios no esten vacios
        if (ftxtCodigo.getText().isEmpty() || txtAutor.getText().isEmpty() 
        || txtTitulo.getText().isEmpty() || txtNoCopias.getText().isEmpty()) {
            validacion = false;
            lblErrorL.setText("*Los primero 4 campos son obligatorios");
            lblErrorL.setVisible(true);
        }
        //Verifica que la fecha tenga un formato correcto
        if (!ftxtFechaPublicacion.getText().equals("    -  -  ")) {
            System.out.println("entro a esta madre");
            if (!isFecha(ftxtFechaPublicacion.getText())) {
                validacion = false;
                labelError(lblErrorL, "*La fecha no esta en el formato correcto");
            }
        }
        if (validacion) {
            libro = new Libro();
            libro.setAutor(txtAutor.getText());
            libro.setCantidad(Integer.parseInt(txtNoCopias.getText()));
            libro.setCodigo(ftxtCodigo.getText());
            libro.setTitulo(txtTitulo.getText());
            if (!txtEditorial.getText().equals("")) {
                libro.setEditorial(txtEditorial.getText());
            }if (!ftxtFechaPublicacion.getText().equals("    -  -  ")) {
                libro.setFechaPublicacion(ftxtFechaPublicacion.getText());
            }
            core.crearLibro(libro);
            //Limpiar Formulario
            cleanAddBook();
            ftxtCodigo.requestFocus();
        }
    }//GEN-LAST:event_btnAddLibroActionPerformed

    private void btnCancelarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLActionPerformed
        cleanAddBook();
        this.repaint();
        jdAddLibro.setVisible(false);
        jdAddLibro.dispose();
    }//GEN-LAST:event_btnCancelarLActionPerformed

    private void btnVerListadoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListadoLActionPerformed
        cleanAddBook();
        core.refrescarTablaLibros(tblListLibros);
        jdListLibros.repaint();
        abrirDialogo(jdListLibros, "Listado de libros");
        cbOpcionFiltroL.requestFocus();
    }//GEN-LAST:event_btnVerListadoLActionPerformed

    private void itmAddCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddCopiasActionPerformed
        String codLibro = JOptionPane.showInputDialog("Digite el codigo del libro");
        if (FileController.verifyFile("libros/"+codLibro+".bin")) {
            String cantidad = JOptionPane.showInputDialog("Ingrese cantidad de copias nuevas");
            while (!isNumeric(cantidad)) {
                mostrarError("Debe ingresar un numero");
                String cant = JOptionPane.showInputDialog("Ingrese cantidad de copias nuevas");
                cantidad = cant;
            }
            core.agregarCopias(Integer.parseInt(cantidad), codLibro);
        }else {
            mostrarError("El libro no existe en el sistema");
        }

    }//GEN-LAST:event_itmAddCopiasActionPerformed

    private void btnFiltrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarLActionPerformed
        if (cbOpcionFiltroL.getSelectedIndex() != -1 && !txtFiltroLibro.getText().isEmpty()) {
            core.filtrarListL(cbOpcionFiltroL.getSelectedIndex(), txtFiltroLibro.getText(),
            tblListLibros);
        }
        //limpiar formulario
        cbOpcionFiltroL.setSelectedIndex(-1);
        txtFiltroLibro.setText("");
    }//GEN-LAST:event_btnFiltrarLActionPerformed

    private void btnAddEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEstActionPerformed
        boolean validacion = true;
        if (!isNumeric(txtCarnet.getText())) {
            validacion = false;
            labelError(lblErrorE, "*Formato de carnet incorrecto");
        }
        int num = Integer.parseInt(txtCodCarrera.getText());
        if (!isNumeric(txtCodCarrera.getText()) || num <= 0 || num >= 6) {
            validacion = false;
            labelError(lblErrorE, "El codigo de carrera no existe");
        }
        if (txtCarnet.getText().isEmpty() || txtNombre.getText().isEmpty() 
                || txtCodCarrera.getText().isEmpty()) {
            lblErrorE.setText("*Los primeros 3 campos son obligatorios");
            lblErrorE.setVisible(true);
        }
        if (!ftxtFechaNac.getText().equals("    -  -  ")) {
            System.out.println("entro a esta madre");
            if (!isFecha(ftxtFechaNac.getText())) {
                validacion = false;
                labelError(lblErrorE, "*La fecha no esta en el formato correcto");
            }
        }
        if (validacion) {
            estudiante = new Estudiante();
            estudiante.setCarnet(txtCarnet.getText());
            estudiante.setCodigoCarrera(Integer.parseInt(txtCodCarrera.getText()));
            estudiante.setNombre(txtNombre.getText());
            if (!ftxtFechaNac.getText().equals("    -  -  ")) {
                estudiante.setFechaNac(ftxtFechaNac.getText());
            }
            core.crearEstudiante(estudiante);
            
            //Limpiar Formulario
            cleanAddStudent();
        }
            txtCarnet.requestFocus();
    }//GEN-LAST:event_btnAddEstActionPerformed

    private void btnCancelarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEstActionPerformed
        cleanAddStudent();
        this.repaint();
        jdAddEstudiante.setVisible(false);
        jdAddEstudiante.dispose();
    }//GEN-LAST:event_btnCancelarEstActionPerformed

    private void btnVerListadoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListadoEActionPerformed
        cleanAddStudent();
        core.refrescarTablaEstudiantes(tblListEstudiantes);
        jdListEstudiantes.repaint();
        abrirDialogo(jdListEstudiantes, "Listado de estudiantes");
        cbOpcionFiltroE.requestFocus();
    }//GEN-LAST:event_btnVerListadoEActionPerformed

    private void btnFiltroEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroEActionPerformed
        if (cbOpcionFiltroE.getSelectedIndex() != -1 && !txtFiltroE.getText().isEmpty()) {
            core.filtrarListE(cbOpcionFiltroE.getSelectedIndex(), txtFiltroE.getText(), tblListEstudiantes);
        }
        //limpiar formulario
        cbOpcionFiltroE.setSelectedIndex(-1);
        txtFiltroE.setText("");
    }//GEN-LAST:event_btnFiltroEActionPerformed

    private void btnCleanFlitroEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanFlitroEActionPerformed
        core.refrescarTablaEstudiantes(tblListEstudiantes);
        cbOpcionFiltroE.setSelectedIndex(-1);
        txtFiltroE.setText("");
        jdAddEstudiante.repaint();
    }//GEN-LAST:event_btnCleanFlitroEActionPerformed

    private void btnCleanFiltroLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanFiltroLActionPerformed
        core.refrescarTablaLibros(tblListLibros);
        cbOpcionFiltroL.setSelectedIndex(-1);
        txtFiltroLibro.setText("");
        jdAddLibro.repaint();
    }//GEN-LAST:event_btnCleanFiltroLActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        boolean flag = true;
        if (!isNumeric(txtCarnetPrestamo.getText())) {
            flag = false;
            labelError(lblErrorP, "*Formato de carnet incorrecto");
        }
        if (!verificarFormatoCodigo(ftxtCodPrestamo1.getText())) {
            flag = false;
            labelError(lblErrorP, "*Formato de codigo erroneo");
        }
        if (txtCarnetPrestamo.getText().isEmpty() || ftxtCodPrestamo1.getText().equals("   -   ")) {
            flag = false;
            labelError(lblErrorP, "*Ambos datos son obligatorios");
        }
        if (flag) {
            core.crearPrestamo(txtCarnetPrestamo.getText(), ftxtCodPrestamo1.getText());
            cleanAddPrestamo();
        }
        txtCarnetPrestamo.requestFocus();
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnCancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPActionPerformed
        cleanAddPrestamo();
        this.repaint();
        jdAddPrestamo.setVisible(false);
        jdAddPrestamo.dispose();
    }//GEN-LAST:event_btnCancelarPActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean flag = true;
        if (!isNumeric(txtCarnetDev.getText())) {
            flag = false;
            labelError(lblErrorDev, "Formato de carnet incorrecto");
        }
        if (!verificarFormatoCodigo(ftxtCodigoDev.getText())) {
            flag = false;
            labelError(lblErrorDev, "Formato de codigo incorrecto");
        }
        if (txtCarnetDev.getText().isEmpty() || ftxtCodigoDev.getText().equals("   -   ")) {
            flag = false;
            labelError(lblErrorDev, "*Ambos datos son obligatorios");
        }
        if (flag) {
            core.calcularTotal(txtCarnetDev.getText(),ftxtCodigoDev.getText());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void itmDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDevolucionActionPerformed
        abrirDialogo(jdDevolucion, "Devolucion");
    }//GEN-LAST:event_itmDevolucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEst;
    private javax.swing.JButton btnAddLibro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarEst;
    private javax.swing.JButton btnCancelarL;
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnCleanFiltroL;
    private javax.swing.JButton btnCleanFlitroE;
    private javax.swing.JButton btnFiltrarL;
    private javax.swing.JButton btnFiltroE;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnVerListadoE;
    private javax.swing.JButton btnVerListadoL;
    private javax.swing.JComboBox<String> cbOpcionFiltroE;
    private javax.swing.JComboBox<String> cbOpcionFiltroL;
    private javax.swing.JFormattedTextField ftxtCodPrestamo1;
    private javax.swing.JFormattedTextField ftxtCodigo;
    private javax.swing.JFormattedTextField ftxtCodigoDev;
    private javax.swing.JFormattedTextField ftxtFechaNac;
    private javax.swing.JFormattedTextField ftxtFechaPublicacion;
    private javax.swing.JMenuItem itmAddCopias;
    private javax.swing.JMenuItem itmAddEstudiante;
    private javax.swing.JMenuItem itmAddLibros;
    private javax.swing.JMenuItem itmAddPrestamo;
    private javax.swing.JMenuItem itmDevolucion;
    private javax.swing.JMenuItem itmVerListEst;
    private javax.swing.JMenuItem itmVerListLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jdAddEstudiante;
    private javax.swing.JDialog jdAddLibro;
    private javax.swing.JDialog jdAddPrestamo;
    private javax.swing.JDialog jdDevolucion;
    private javax.swing.JDialog jdListEstudiantes;
    private javax.swing.JDialog jdListLibros;
    private javax.swing.JLabel lblErrorDev;
    private javax.swing.JLabel lblErrorE;
    private javax.swing.JLabel lblErrorL;
    private javax.swing.JLabel lblErrorP;
    private javax.swing.JMenu menuEstudiante;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JTable tblListEstudiantes;
    private javax.swing.JTable tblListLibros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCarnetDev;
    private javax.swing.JTextField txtCarnetPrestamo;
    private javax.swing.JTextField txtCodCarrera;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFiltroE;
    private javax.swing.JTextField txtFiltroLibro;
    private javax.swing.JTextField txtNoCopias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
    
    private void abrirDialogo(javax.swing.JDialog jd, String title){
        jd.setTitle(title);
        jd.setLocationRelativeTo(null);
        jd.setResizable(false);
        jd.setVisible(true);
    }
    
    private boolean isNumeric(String s){
        try {
            int n = Integer.parseInt(s);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean isFecha(String f){
        try {
            LocalDate fecha = LocalDate.parse(f);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    public static boolean verificarFormatoCodigo(String codigo){
        boolean bandera = false;
        
        String[] seccionesCodigo = codigo.split("-");
        //Verifica que existan 3 caracteres de cada lado
        if (seccionesCodigo[0].length() == 3 && seccionesCodigo[1].length() == 3) {
            
            try{
                Integer.parseInt(seccionesCodigo[0]);
                if (seccionesCodigo[1].equals(seccionesCodigo[1].toUpperCase())) {
                    bandera = true;
                }
            }catch(Exception e){
                bandera = false;
            }
            
        }else{
            bandera = false;
        }
        return bandera;
    }
    
    public static void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje, 
        "Error", JOptionPane.WARNING_MESSAGE);
    }
    
    public static void mostrarInfo(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje, 
        "Informacion", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void labelError(javax.swing.JLabel lbl, String msj){
        lbl.setText(msj);
        lbl.setVisible(true);
    }
    
    private void cleanAddBook(){
        txtAutor.setText("");
        txtCarnet.setText("");
        txtEditorial.setText("");
        txtTitulo.setText("");
        ftxtCodigo.setText("");
        txtNoCopias.setText("");
        ftxtFechaPublicacion.setText("");
        lblErrorL.setVisible(false);
    }
    
    private void cleanAddStudent(){
        txtCarnet.setText("");
        txtCodCarrera.setText("");
        txtNombre.setText("");
        ftxtFechaNac.setText("");
        lblErrorE.setVisible(false);
    }
    
    private void cleanAddPrestamo(){
        txtCarnetPrestamo.setText("");
        ftxtCodPrestamo1.setText("");
        lblErrorP.setVisible(false);
    }
   
}
